[package]
name = "stock"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
anyhow = "1.0"
